austin-scott19.github.io
My project portfolio

### 360

<script src='//vizor.io/static/scripts/vizor-360-embed.js' data-vizorurl='//vizor.io/embed/scottie6561/360'></script>

Project Description

I call my project "Busy at Lunch" and wanted to show what it looks like at lunch at EHS. This shows everyone converstating and eating, as well as the cliques that they are in. I hope you see how each individual interacts during lunch with others. 
